### ISSUE TITLE
Doesn't work anymore. Any chance for a fix?

### ISSUE THREAD

**Issue by azumbrunnen** [vikramezhil/DroidSpeech2.0#17]
2021-03-18 12:03:27.373 25037-25037/com.example.gmnext E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gmnext, PID: 25037
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gmnext/com.example.gmnext.MainActivity}: java.lang.IllegalStateException: RecognizerIntent.getVoiceDetailsIntent(app) must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3572)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3729)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)
     Caused by: java.lang.IllegalStateException: RecognizerIntent.getVoiceDetailsIntent(app) must not be null
        at github.com.vikramezhil.dks.speech.Dks.<init>(Dks.kt:37)
        at com.example.gmnext.MainActivity.onCreate(MainActivity.kt:53)
        at android.app.Activity.performCreate(Activity.java:7967)
        at android.app.Activity.performCreate(Activity.java:7947)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3545)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3729) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)

**Comment by HansCB** [comment]
My workaround:
1. Download the code.
2. Copy the library 'dks' from the code into your project
3.  add ` classpath "org.jetbrains.dokka:dokka-gradle-plugin:0.10.1"` to the dependencies in your project gradle
4. replace `implementation 'com.github.vikramezhil:DroidSpeech2.0:vx.y' ` with `implementation project(path: ':dks')`
5. change in dks\speech\Dks  line 37:` override var languageDetailsIntent: Intent = Intent(app)` to `override var languageDetailsIntent: Intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH)`
6.  add to your manifest: ` <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>`

**Comment by greencow555** [comment]
I second this post. Thought this library was going to solve all my problems, but doesn't work from step 1. DKS cannot be imported... please fix.

**Comment by ljsharp** [comment]
> I second this post. Thought this library was going to solve all my problems, but doesn't work from step 1. DKS cannot be imported... please fix.

You need to put the dks folder in your project directory like this your_project_name/put_it_here and then update the follow code in settings.gradle 

include **':dks'**, ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()
.........
,,,,,,,,

Sync your project and the library will be imported into the project.
