### ISSUE TITLE
Crash on java implementation

### ISSUE THREAD

**Issue by dkatitest** [vikramezhil/DroidSpeech2.0#6]
Hello. Thanks for that nice work.

while trying to run your example,i got error

java.lang.IllegalStateException: RecognizerIntent.getVoiceDetailsIntent(app) must not be null
at github.com.vikramezhil.dks.speech.Dks.<init>(Dks.kt:37)

My code: 

```
 
Dks speech = new Dks(getApplication(), getSupportFragmentManager(), new DksListener() {
            @Override
            public void onDksLiveSpeechResult(@NotNull String s) {
                Log.e("1111111",s);
            }

            @Override
            public void onDksFinalSpeechResult(@NotNull String s) {
                Log.e("2222222",s);
            }

            @Override
            public void onDksLiveSpeechFrequency(float v) {
                Log.e("33333",v+"");
            }

            @Override
            public void onDksLanguagesAvailable(@org.jetbrains.annotations.Nullable String s, @org.jetbrains.annotations.Nullable ArrayList<String> arrayList) {
                String a="";
                if (arrayList!=null && arrayList.size()>0) {
                    for (String z : arrayList) {
                        a += " " + z;
                    }
                    Log.e("444444", a);
                }
            }

            @Override
            public void onDksSpeechError(@NotNull String s) {
                Log.e("55555",s);
            }
        });
        speech.setOneStepResultVerify(true);
        speech.startSpeechRecognition();
 
```

**Comment by vikramezhil** [comment]
Hello, can you please provide me the entire log stack trace along with your activity class? I checked it from my end and I wasn't able to reproduce this from my end.

It seems your **getApplication()** is returning null.

You can also refer to the [java example class](https://github.com/vikramezhil/DroidSpeech2.0/blob/master/DroidKotSpeech/app/src/main/java/github/com/vikramezhil/droidkotspeechexample/MainJavaActivity.java) in case you have any doubts.

**Comment by creationspirit** [comment]
@vikramezhil I encountered the same problem. It seems this here is a problem https://developer.android.com/reference/android/speech/RecognizerIntent#getVoiceDetailsIntent(android.content.Context)

There it says this. `This is based on the value specified by the voice search Activity in DETAILS_META_DATA, and if this is not specified, will return null. Also if there is no chosen default to resolve for ACTION_WEB_SEARCH, this will return null.`

**Comment by vikramezhil** [comment]
@creationspirit  Thanks for looking into this, let me have a look. Will update back here once I analyse it.

**Comment by don41382** [comment]
Same issue over here! I tried to run the example app with Andriod Studio and app crashes right after launch:

```2020-05-26 11:03:32.092 10968-10968/? E/otspeechexampl: Unknown bits set in runtime_flags: 0x8000
2020-05-26 11:03:32.513 10968-10968/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: github.com.vikramezhil.droidkotspeechexample, PID: 10968
    java.lang.RuntimeException: Unable to start activity ComponentInfo{github.com.vikramezhil.droidkotspeechexample/github.com.vikramezhil.droidkotspeechexample.MainKotlinActivity}: java.lang.IllegalStateException: RecognizerIntent.getVoiceDetailsIntent(app) must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: RecognizerIntent.getVoiceDetailsIntent(app) must not be null
        at github.com.vikramezhil.dks.speech.Dks.<init>(Dks.kt:37)
        at github.com.vikramezhil.droidkotspeechexample.MainKotlinActivity.onCreate(MainKotlinActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)```

**Comment by hviana** [comment]
same problem in kotlin example

**Comment by noloman** [comment]
hi, I'm having exactly the same problem

**Comment by flauschtrud** [comment]
Same here with Java and API Level 30. Are there any new insights on this issue?

**Comment by sommovir** [comment]
any news about this bug  ? I would like to use this API but it crash on same bug of you guys ? any workaround ?

**Comment by HansCB** [comment]
I have the same bug on all android 11 devices.
My solution: I dowloaded the code and changed in DKs.kt on line 37 
`override var languageDetailsIntent: Intent = Intent(app)` to
`override var languageDetailsIntent: Intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH)`
Then I copied the dks pakage to my project and changed the app gradle from
`implementation 'com.github.vikramezhil:DroidSpeech2.0:1.2'` to
`  implementation project(path: ':dks')`
and it works.
Its a workaround until it's fixed. I hope this workaround is allowed under the Apache 2 Licence
